language: generic

sudo: required


before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"

script:
  - chmod +x shell/checker-remix.sh
  - bash shell/checker-remix.sh
